### ISSUE TITLE
Using the `$casts` it showing empty

### ISSUE THREAD

**Issue by khanakia** [invaders-xx/filament-jsoneditor#27]
I have a Mysql json type field `$table->json('functions_stack');`

When i use the `$casts` it shows empty but when i remove the $casts it works fines

```php
class TaskJob extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $casts = [
        'functions_stack' => 'json',
    ];
}
```

![Screenshot 2023-10-12 at 6 51 46 PM](https://github.com/invaders-xx/filament-jsoneditor/assets/2174170/6d520ee2-6cf0-41be-8e32-99a07115cda4)

### When $casts removed it works
![Screenshot 2023-10-12 at 6 52 30 PM](https://github.com/invaders-xx/filament-jsoneditor/assets/2174170/b19bce55-4238-401a-976b-f4b40b7cc3d1)

**Comment by khanakia** [comment]
I got it fixed by using isJson() by using it like below

```php
\InvadersXX\FilamentJsoneditor\Forms\JSONEditor::make('functions_stack')->isJson()
```

**Comment by harlamoff** [comment]
In version JSONEditor 3.1 there is a problem with saving the field.
(Mysql json)


<img width="482" alt="Screenshot 2023-11-27 at 17 35 14" src="https://github.com/invaders-xx/filament-jsoneditor/assets/21295451/c0416eea-3ca7-4e39-90b3-7f6fa1fcb7ad">

After making changes:
<img width="369" alt="Screenshot 2023-11-27 at 17 35 45" src="https://github.com/invaders-xx/filament-jsoneditor/assets/21295451/3ee7d166-70ac-4d53-9dc6-8b0f80765356">


Code fix it:
```
            ->dehydrateStateUsing(function ($state) {
                if(is_string($state)){
                    return json_decode($state, true);
                }
                return $state;
            })
```

**Comment by hanaexcl** [comment]
> In version JSONEditor 3.1 there is a problem with saving the field. (Mysql json)
> 
> <img alt="Screenshot 2023-11-27 at 17 35 14" width="482" src="https://private-user-images.githubusercontent.com/21295451/285907179-c0416eea-3ca7-4e39-90b3-7f6fa1fcb7ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDkwMDgsIm5iZiI6MTcwMTg0ODcwOCwicGF0aCI6Ii8yMTI5NTQ1MS8yODU5MDcxNzktYzA0MTZlZWEtM2NhNy00ZTM5LTkwYjMtN2Y2ZmExZmNiN2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA3NDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOTk3MTlmMjgyNjdkZGFiMjM4ZjJiZGRhYTA4OWY1YjNlNjhhYjRkNzc5MzdiMDkzZDg3NGJjMTBiYmYxOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CofLb67HlMqC0F6_wDmGdlBlvCbMLfiP3fMZivOQOv0">
> After making changes: <img alt="Screenshot 2023-11-27 at 17 35 45" width="369" src="https://private-user-images.githubusercontent.com/21295451/285907212-3ee7d166-70ac-4d53-9dc6-8b0f80765356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDkwMDgsIm5iZiI6MTcwMTg0ODcwOCwicGF0aCI6Ii8yMTI5NTQ1MS8yODU5MDcyMTItM2VlN2QxNjYtNzBhYy00ZDUzLTlkYzYtOGIwZjgwNzY1MzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA3NDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZDBmNWZiY2I3ZDBjYmFiYTBhNjIxYmQ0ZjhjMmM4YzQyZGFhMDQyMTFjODgyYTQ4YmY0YTJkNGYxMjUzMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mz1rK0tKDkbuYQVJoT4avOeiFBRU0-4WELnhr_lVEc8">
> 
> Code fix it:
> 
> ```
>             ->dehydrateStateUsing(function ($state) {
>                 if(is_string($state)){
>                     return json_decode($state, true);
>                 }
>                 return $state;
>             })
> ```

I have the same issue.
filament: v3.0.102
jsoneditor: v3.1

**Comment by iztok** [comment]
I had the same problem and solved it with https://github.com/invaders-xx/filament-jsoneditor/issues/27#issuecomment-1827958924 

I have a JSON columns which has a JSON cast.
