### ISSUE TITLE
'json' and 'array' cast columns are escaped when they shouldn't be

### ISSUE THREAD

**Issue by idealerror** [invaders-xx/filament-jsoneditor#29]
I'm trying to update an existing 'array' column that originally shows as 

```json
[ 
    "email"
]
```

When I save it, the column gets stored as:

```json
"[\n  \"email\"\n]"
```

How do I stop it from sanitizing the column?  Is this a filament setting or an issue with this package?

**Comment by idealerror** [comment]
Nevermind, this is no longer an issue.

**Comment by tipmisle** [comment]
@idealerror Hey, I have the same problem, what fixed it for you? Thanks

I have set $casts for my field as array, and initially it shows ok but after saving it gets mangled

`"{\"title\":`

**Comment by tipmisle** [comment]
nevermind: I fixed it with:
https://github.com/invaders-xx/filament-jsoneditor/issues/27#issuecomment-1827958924
`->dehydrateStateUsing(function ($state) {
                if(is_string($state)){
                    return json_decode($state, true);
                }
                return $state;
            })`

Full field:
```
\InvadersXX\FilamentJsoneditor\Forms\JSONEditor::make('default_settings')
					->modes(['code', 'form', 'text', 'tree', 'view', 'preview'])
					->dehydrateStateUsing(function ($state) {
						if(is_string($state)){
							return json_decode($state, true);
						}
						return $state;
					}),
```
